### ISSUE TITLE
Is world not infinite with this mod

### ISSUE THREAD

**Issue by BurovB** [Zeno410/Climate-Control#11]
What I mean? On your preview I saw that climate are changed from northern pole to south pole. But minecraft' world is infinite and because of this, some of the climate zones must be infinite. It's two belts in the North and South pole, because if the infinite were the other belt then the player would not be able to visit those that are after them. So in theory this mod should limit the size of the world, what would correctly generate

**Comment by Zeno410** [comment]
It only generates the bands if the bandedClimate option is on. By default, it's off and the climates are placed as blobs like vanilla does, but with a number of options to change frequencies, placements, and sizes. If bands are on, they do cycle. Limiting world size is way out of scope for this mod.
