### ISSUE TITLE
[Time Sensitive- 1.7.10] How to add compatibility for custom biomes via the API?

### ISSUE THREAD

**Issue by Zero-ui9** [Zeno410/Climate-Control#12]
We noticed that none of the new Chromaticraft biomes were not spawning in Climate Control worlds, upon looking at climate control code it appears that compatibility is manually hardcoded on a biome by biome basis. Obviously this means that new biomes have no compatibility and do not spawn. This is an extremely serious issue and we are trying to fix this as soon as possible. We noticed while looking through the Climate Control code that much of this seems to involve API code and as a result we're wondering if its possible through the Climate Control API to add this compatibility, effectively taking the place of the config. Basically what we want to do is have Chromaticraft tell Climate Control to add the new biomes to the spawn tables with specified parameters such as spawn weight. If this issue is not fixed soon, the release of V17 ChC will become extremely problematic for those using Climate Control. Again, we're not asking for you to update the compatibility because we realize this may not be possible to do quickly, what we're asking for is information for @ReikaKalseki can implement this compatibility himself.

**Comment by ReikaKalseki** [comment]
Basically, unless I fix this from my end, once I release v17 - which is already significantly overdue for its testing period, and which I want to release soon - everyone using ClimateControl will not have access to the new ChromatiCraft biomes. Additionally, I am trying to get my dev server set up - we were previously hoping to do so today or tomorrow - and we right now cannot unless we elect to remove ClimateControl entirely (which we very much do not want to do).

As for the actual behavior, all I care about is being able to add the new biomes to the list that ClimateControl will try to spawn. Whether it shows up in the config or not is irrelevant (provided parameters like weight are controllable from somewhere), as is anything like what climate region it gets associated with.

And if this is somehow incompatible with the existing your-side compatibility, then I am perfectly willing to handle it all on my end. Just tell me how to override the native compat.

**Comment by ReikaKalseki** [comment]
An update: I have an interim plan for the dev server, involving an ASM patch into ReikasPackage to change `freshBiomeSetting()` to return a custom `BiomeSettings` object (effectively an updated version of `ReikasBiomeSettings`). However, I imagine that you do not want me using this in release code, so a proper solution is still needed, if mildly less urgently.

**Comment by ReikaKalseki** [comment]
I have released the ASM patch in the public copy of ChromatiCraft due to a lack of other options.
