### ISSUE TITLE
Undivided biome placement [Hot & Snowy Climates]

### ISSUE THREAD

**Issue by Quizer9O8** [Zeno410/Climate-Control#14]
I've noticed that in this version of CC (1.10) a lot of snowy climates are scattered in strange spots in different seeds. This wouldn't be a big issue for me normally but those snowy climates are literally everywhere and sometimes too close to each other. Hot climates are also scarce and way smaller than vanilla generates them.

Is there an option in the config file to adjust the spawn rate of climates? If not can you make one?
![too much white](https://cloud.githubusercontent.com/assets/19509275/24657645/5c00605e-1947-11e7-83e3-ef9aa3437265.png)

**Comment by Zeno410** [comment]
The climate frequency parameters alter the spawn rate of climates.
