### ISSUE TITLE
[Request] Add a Temperate Zone

### ISSUE THREAD

**Issue by ghost** [Zeno410/Climate-Control#18]
I was hoping MEDIUM would place biomes between COOL and WARM, but instead it scatters them throughout. Right now, the 'gradient' of temperatures is too sharp in places. This could be solved by adding an extra climate zone (TEMPERATE).
Side note: It occurred to me that it would make this mod more flexible if it was made so one could add climate zones themselves, defining min/max temperatures in the config. But that is just me overthinking it ;)

**Comment by Zeno410** [comment]
I don't intend to interpolate climate zones. It would be quite a project. The temperature gradient can be reduced by using full size climate zones.

**Comment by Zeno410** [comment]
I don't intend to interpolate climate zones. It would be quite a project. The temperature gradient can be reduced by using full size climate zones.
