### ISSUE TITLE
Request to choose which size island to spawn on

### ISSUE THREAD

**Issue by NostalgicLorikeet** [Zeno410/Climate-Control#26]
Not sure where I'd put a feature request (or if you take them), but this would basically be like `forceStartContinent` but the user chooses which size the continent is. From what I understand it forces a small (2000x4000) continent at spawn but it would be cool to spawn on either a large continent or medium size island.

**Comment by Zeno410** [comment]
Added medium and large continents in 0.9.5.1. Sorry, but islands are a bit tricky because of climate issues.

**Comment by Zeno410** [comment]
If you want to start on a medium island with other land available, you could start with a config allowing only medium islands, and then edit the config to allow other land masses. (in the worldspecificconfig folder of the save folder; once a world has been made Geo ignores the general config for it) Chunk wall prevention will shield you; the world will transition to the new configs starting roughly 1000 blocks from anywhere explored, or anywhere tested when it's trying to place spawn (roughly, anyplace closer to 0,0 than where you start.)
