### ISSUE TITLE
IndexOutOfBoundException in a large modpack

### ISSUE THREAD

**Issue by Biviho** [Zeno410/Climate-Control#27]
hi, i'm having an issue in a pretty large modpack that i previously didn't have: 

[the crash](https://mclo.gs/Dk7jIsm)

i have RTG Unofficial, wich add compatibility with REI, i must have updated something or changed something in some config and i don't remember it, but going back to the modpack give me this issue.

i wasn't able to pinpoint the mod who cause this, if there is. I tested with only the biome mods and i still got the crash, also i tested with resetting the config back, nothing

if you need more information i can do more tests, let me know

**Comment by Zeno410** [comment]
Geographicraft is not currently written to handle more than 256 biomes. I will look into changing it.

**Comment by Biviho** [comment]
i see, ty, ot would be really great!

**Comment by Zeno410** [comment]
Fixed in latest version
