### ISSUE TITLE
Rtg and CC

### ISSUE THREAD

**Issue by dahjin** [Zeno410/Climate-Control#7]
When using this RTG and CC I get huge and super dense forests which i have no control over fixing at all. After further testing it seems its a thing between RTG CC and BoP

http://i.imgur.com/jVhARho.jpg

**Comment by Zeno410** [comment]
This is BoP; they place a huge number of trees. It's not too different in a BoP world, although some because their terrain is rougher and supports fewer spawn. The way to adjust this is the BoP configs.
